# Generated by Django 3.2.8 on 2022-02-14 23:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AddField(
            model_name='query',
            name='start_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2022, 2, 14, 23, 10, 47, 710190, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='query',
            name='prod_article',
            field=models.CharField(max_length=30, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_text',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Запрос / Ключевое слово'),
        ),
    ]
