# Generated by Django 3.2.8 on 2022-02-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220215_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='start_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
