# Generated by Django 3.2.8 on 2022-02-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_query_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='start_date',
            field=models.DateField(db_index=True, default='15.02'),
        ),
    ]
