# Generated by Django 3.2.8 on 2022-02-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220216_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_text',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Запрос / Ключевое слово'),
        ),
        migrations.AlterField(
            model_name='result',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, unique=True, verbose_name='Дата'),
        ),
    ]
