# Generated by Django 3.2.8 on 2022-02-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220216_0124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ('date',), 'verbose_name': 'Результат', 'verbose_name_plural': 'Результаты'},
        ),
        migrations.AlterField(
            model_name='result',
            name='position',
            field=models.CharField(default=None, max_length=5, verbose_name='Позиция'),
        ),
    ]
